airport_code = {
    'atl': "Hartsfield-Jackson International Airport",     
    'dfw': "Dallas/Fort Worth International Airport",
    'den': "Denver International Airport",
    'ord': "O'Hare International Airport",
    'lax': "Los Angeles International Airport",
    'clt': "Charlotte Douglas International Airport",
    'las': "Harry Reid International Airport",
    'phx': "Phoenix Sky Harbor International Airport",
    'mco': "Orlando International Airport",
    'sea': "Seattle–Tacoma International Airport",
    'mia': "Miami International Airport",
    'iah': "George Bush Intercontinental Airport",
    'jfk': "John F. Kennedy International Airport",
    'fll': "Fort Lauderdale–Hollywood International Airport",
    'ewr': "Newark Liberty International Airport",
    'sfo': "San Francisco International Airport",
    'msp': "Minneapolis–Saint Paul International Airport",
    'dtw': "Detroit Metropolitan Airport",
    'bos': "Logan International Airport",
    'slc': "Salt Lake City International Airport",
    'phl': "Philadelphia International Airport",
    'bwi': "Baltimore/Washington International Airport",
    'tpa': "Tampa International Airport",
    'san': "San Diego International Airport",
    'mdw': "Midway International Airport",
    'lga': "LaGuardia Airport",
    'bna': "Nashville International Airport",
    'iad': "Washington Dulles International Airport"
}